MIN_PASSWORD_LENGTH = 10
RANDOM_PASSWORD_LENGTH = 16
USER_TUPLE_LENGTH = 5
ROLE_TUPLE_LENGTH = 2

# Response type
ADD_RECORD_TO_DATABASE = "NEW RECORD HAS BEEN ADDED TO DATABASE"
DELETE_RECORD_FROM_DATABASE = "RECORD HAS BEEN REMOVED FROM DATABASE"
FOUND_RECORD_IN_DATABASE = "RECORD(S) WAS/WERE FOUND IN DATABASE"
UPDATE_RECORD_IN_DATABASE = "RECORD HAS BEEN UPDATED"

# Exception/Error Type
NOT_FOUND = "NOT FOUND"
RECORD_NOT_GET = "DATA CANNOT GET FROM DATABASE"
ALREADY_EXISTED = "ALREADY EXISTED"
RECORD_NOT_ADD = "NEW RECORD HAS NOT BEEN ADDED"
RECORD_NOT_UPDATE = "RECORD HAS NOT BEEN UPDATED"
RECORD_NOT_REMOVE = "RECORD HAS NOT BEEN REMOVED"

JSON_SCHEMA_VALIDATION_FAILED = "JSON SCHEMA VALIDATION FAILED"
DATABASE_CONNECTION_FAILED = "DATABASE CONNECTION FAILED"
DATABASE_ERROR = "DATABASE ERROR"
QUERY_EXECUTE_FAILED = "QUERY EXECUTE FAILED"

VALUE_ERROR = "INAPPROPRIATE ARGUMENT VALUE (OF CORRECT TYPE)"
EXCEPTION_HANDLE = "EXCEPTION HAS BEEN HANDLED"


