MIN_PASSWORD_LENGTH = 10
RANDOM_PASSWORD_LENGTH = 16

# Response type
ADD_RECORD_TO_DATABASE = "NEW RECORD HAS BEEN ADDED TO DATABASE"
RECORD_NOT_ADDED_TO_DATABASE = "NEW RECORD HAS NOT BEEN ADDED TO DATABASE"
DELETE_RECORD_FROM_DATABASE = "RECORD HAS BEEN REMOVED FROM DATABASE"
