MIN_PASSWORD_LENGTH = 10
RANDOM_PASSWORD_LENGTH = 16
USER_TUPLE_LENGTH = 5
ROLE_TUPLE_LENGTH = 2

# Response type
ADD_RECORD_TO_DATABASE = "NEW RECORD HAS BEEN ADDED TO DATABASE"
RECORD_NOT_ADDED_TO_DATABASE = "NEW RECORD HAS NOT BEEN ADDED TO DATABASE"
DELETE_RECORD_FROM_DATABASE = "RECORD HAS BEEN REMOVED FROM DATABASE"
RECORD_NOT_REMOVED_FROM_DATABASE = "RECORD HAS NOT BEEN REMOVED FROM DATABASE"
WRONG_DATA_FIELD_IN_REQUEST = "DATA FIELD(S) IN REQUEST IS NOT CORRECT"
WRONG_DATA_FIELD_IN_RESPONSE = "DATA FIELD(S) IN RESPONSE IS NOT CORRECT"
EXCEPTION_HANDLE = "EXCEPTION HAS BEEN HANDLED"
NOT_FOUND = "NOT FOUND"
FOUND_RECORD_IN_DATABASE = "RECORD(S) WAS/WERE FOUND IN DATABASE"
DATA_CANNOT_GET_FROM_DATABASE = "DATA CANNOT GET FROM DATABASE"
JSON_SCHEMA_VALIDATION_FAILED = "JSON SCHEMA VALIDATION FAILED"
